# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean and Build with Gradle
      run: ./gradlew clean build

#    - name: Build and Push Docker Image
#      uses: mr-smithers-excellent/docker-build-push@v4
#      with:
#        image: emryduman/emry-repo-01   # Change this to your Docker Hub repo name
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}       # Set this secret in your repo settings
#        password: ${{ secrets.DOCKER_PASSWORD }}       # Set this secret in your repo settings

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t emryduman/emry-repo-01:latest .

    - name: Push Docker Image
      run: docker push emryduman/emry-repo-01:latest


      
